name = "image-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "kabirx-db"
database_id = "19906e55-75e6-444f-a5d1-e4ecef17d021"

